# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c012771010f21d8f30ebd1a666dea012b3073d8e0677761ead5a51c514b609e06d77f387fda66185fe0fff5d58a50c4bbcc5ccb640e2364e9809fe2992018e8

test:
  secret_key_base: 7849463e1843aa4fbf4a7ee821fa5af944db98251305901e2fe0a04a750e7bf9108aef562af6f9fe3a95deab4cde6aa59fb2200b4adf6614d2ab70ef32140993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
